name: Create Release

on:
  push:
    tags:
      - 'v*'  # Запускается при пуше тега вида v1.0.0, v2.3.4 и т.д.

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get Tag Name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          body: |
            🎉 Новый релиз ${{ env.TAG_NAME }}!
            - Автоматически сгенерирован GitHub Actions
            **Full Changelog**: https://github.com/bandysiklt/test_release/compare/v.1.0.0...v.1.0.2
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
